resource_group_name    = "kv_terraform_rg"
location               = "West Europe"
keyvault_name          = "JoseAZ"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"
